CREATE SCHEMA `627089-doingsdone` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `627089-doingsdone`;
CREATE TABLE category (
id INT AUTO_INCREMENT PRIMARY KEY, 
name CHAR(30) NOT NULL);

CREATE TABLE user (
id INT AUTO_INCREMENT PRIMARY KEY, 
name CHAR(30) NOT NULL UNIQUE,
email CHAR(64) NOT NULL UNIQUE,
password CHAR(64) NOT NULL,
dt_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE task (
id INT AUTO_INCREMENT PRIMARY KEY,
name CHAR(64) NOT NULL,
dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
dt_complete TIMESTAMP,
dt_due TIMESTAMP NOT NULL,
status INT DEFAULT 0,
file CHAR(30) DEFAULT '',
category_id INT NOT NULL,
user_id INT NOT NULL);
